const Data = [
    {
        Name: "Neharika",
        Roll_Number: 1,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
    },
    {
        Name: "Ravi Teja",
        Roll_Number: 2,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
    },
    {
        Name: "Tej Prabhakar",
        Roll_Number: 3,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Rini",
        Roll_Number: 4,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Mounika",
        Roll_Number: 5,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Bini",
        Roll_Number: 6,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Hepbzibah",
        Roll_Number: 7,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Havilah",
        Roll_Number: 8,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Alen",
        Roll_Number: 9,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
      {
        Name: "Aakarsh Raj",
        Roll_Number: 10,
        English: 90,
        Science: 87,
        Telugu: 98,
        Hindi:40,
        Social: 89,
        Extra_activities: 90,
        Total_marks: {},
      },
    ];
  
  export default Data;